# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HamIntercessionFriendRequestsTest' do
  pod 'Firebase/Core'

pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Analytics'
pod 'Firebase/InAppMessaging'
pod 'Firebase/Storage'
end
